## NumPY

The NumPy library is the core library for scientific computing in Python. It provides a high-performance multidimensional array
object, and tools for

Use the following import convention:

In [1]:
import numpy as np

### Asking For Help

In [21]:
np.info(np.ndarray.dtype)

Data-type of the array's elements.

.. warning::

    Setting ``arr.dtype`` is discouraged and may be deprecated in the
    future.  Setting will replace the ``dtype`` without modifying the
    memory (see also `ndarray.view` and `ndarray.astype`).

Parameters
----------
None

Returns
-------
d : numpy dtype object

See Also
--------
ndarray.astype : Cast the values contained in the array to a new data-type.
ndarray.view : Create a view of the same data but a different data-type.
numpy.dtype

Examples
--------
>>> x
array([[0, 1],
       [2, 3]])
>>> x.dtype
dtype('int32')
>>> type(x.dtype)
<type 'numpy.dtype'>


### NumPy Arrays

**Creating Arrays**

In [2]:
a = np.array([1,2,3])  # 1 Dimensional Array
a

array([1, 2, 3])

In [6]:
b = np.array([(1.5,2,3), (4,5,6)], dtype= float)  # 2 Dimensional Array
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [8]:
c = np.array([[(1,2,3),(4,5,6)],[(7,8,9),(1.5,2.5,3.5)]], dtype=float)  # 3 Dimensional Array
c

array([[[1. , 2. , 3. ],
        [4. , 5. , 6. ]],

       [[7. , 8. , 9. ],
        [1.5, 2.5, 3.5]]])

Initial Placeholders

In [10]:
np.zeros((3,4))  # Create an array of zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [13]:
np.ones((2,3,4), dtype = np.int16)  # Create an array of ones

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [14]:
d = np.arange(10,25,5)  # Create an array of evenly spaced values (step value)
d

array([10, 15, 20])

In [15]:
np.linspace(0,2,9)  # Create an array of evenly spaced values (number of samples)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [17]:
e = np.full((2,2),7)  # Create a constant array
e

array([[7, 7],
       [7, 7]])

In [18]:
f = np.eye(2)  # Create a 2X2 identity matrix
f

array([[1., 0.],
       [0., 1.]])

In [19]:
np.random.random((2,2))  # Create an array with random values

array([[0.89117884, 0.32979646],
       [0.15762879, 0.23834271]])

In [20]:
np.empty((3,2))  # Create an empty array

array([[1.5, 2. ],
       [3. , 4. ],
       [5. , 6. ]])

### Saving & Loading On Disk

In [ ]:
# np.save("my_array", a)

# np.savez("array.npz", a,b)

# np.load("my_array.npy")

### Saving & Loading Text Files

In [ ]:
# np.loadtxt("myfile.txt")

# np.genfromtxt("my_file.csv", delimeter =",")

# np.savetxt("my_array.txt", a, delimeter =" ")

### Inspecting Your Array

In [22]:
x = np.array([1,2,3]) # Array dimensions

x.shape

(3,)

In [23]:
y = np.array([(1,2,3),(4,5,6)])

y.shape

(2, 3)

In [25]:
print(f"x length is {len(x)}")

print(f"y length is {len(y)}")

x length is 3
y length is 2


In [32]:
x.ndim  # Number of array dimensions

1

In [33]:
print(f"y number of array dimensions {y.ndim}")

y number of array dimensions 2


In [31]:
x.size  # Number of array elements

3

In [34]:
print(f"y number of array elements {y.size}")

y number of array elements 6


In [35]:
z = np.array([[(1,2,3),(4,5,6)],[(7,8,9),(1.5,2.5,3.5)]], dtype=float) # Data type of array elements

z.dtype

dtype('float64')

In [36]:
z = np.array([[(1,2,3),(4,5,6)],[(7,8,9),(1.5,2.5,3.5)]], dtype=int)

z.dtype

dtype('int32')

In [40]:
z = np.array([[(1,2,3),(4,5,6)],[(7,8,9),(1.5,2.5,3.5)]], dtype=float)

z.dtype.name  # Name of data type

'float64'

In [42]:
z.astype(int)  # Convert an array to a different type


array([[[1, 2, 3],
        [4, 5, 6]],

       [[7, 8, 9],
        [1, 2, 3]]])

### Data Types

In [44]:
np.int64   # Signed 64-bit integer types

numpy.int64

In [46]:
type(1)  # Example

int

In [45]:
np.float32  # Standard double-precision floating point

numpy.float32

In [47]:
type(1.5)  # Example

float

In [49]:
np.complex128  # Complex numbers represented by 128 floats

numpy.complex128

In [50]:
type((3 + 7j))

complex

In [52]:
np.bool_  # Boolean type storing TRUE and FALSE values

numpy.bool_

In [53]:
type(True)

bool

In [54]:
np.object_  # Python object type

numpy.object_

In [55]:
np.string_  # Fixed-length string type

numpy.bytes_

In [56]:
np.unicode_  # Fixed-length unicode type

numpy.str_

### Array Mathematics

Arithmetic Operations

In [59]:
x = np.array([(1,2,3),(4,5,6)])

y = np.array([(10,12,13),(14,15,16)])

sub = x - y   # ubtraction
 
sub

array([[ -9, -10, -10],
       [-10, -10, -10]])

In [60]:
np.subtract(x,y)

array([[ -9, -10, -10],
       [-10, -10, -10]])

In [61]:
x + y  # Addition

array([[11, 14, 16],
       [18, 20, 22]])

In [62]:
np.add(x,y)

array([[11, 14, 16],
       [18, 20, 22]])

In [63]:
x / y  # Division

array([[0.1       , 0.16666667, 0.23076923],
       [0.28571429, 0.33333333, 0.375     ]])

In [64]:
np.divide(x,y)

array([[0.1       , 0.16666667, 0.23076923],
       [0.28571429, 0.33333333, 0.375     ]])

In [65]:
x * y  # Multiplication

array([[10, 24, 39],
       [56, 75, 96]])

In [66]:
np.multiply(x,y)

array([[10, 24, 39],
       [56, 75, 96]])

In [68]:
z = np.array([1,5,7])

np.exp(z)  # Exponentiation

array([   2.71828183,  148.4131591 , 1096.63315843])

In [70]:
np.sqrt(z)  # Square root

array([1.        , 2.23606798, 2.64575131])

In [71]:
np.sin(z)  # Print sines of an array

array([ 0.84147098, -0.95892427,  0.6569866 ])

In [72]:
np.cos(z)  # Element-wise cosine

array([0.54030231, 0.28366219, 0.75390225])

In [73]:
np.log(z)  # Element-wise natural logarithm

array([0.        , 1.60943791, 1.94591015])

Comparison

In [85]:
x = np.array([(1,2,3),(4,5,6)])

y = np.array([(10,2,13),(14,5,16)])

np.array_equal(x,y)  # Element-wise comparison

False

In [83]:
x < 2

array([[False, False, False]])

Aggregate Functions

In [86]:
x = np.array([(1,2,3),(4,5,6)])

x.sum()   # Array-wise sum

21

In [88]:
x.min()  # Array-wise minimum value

1

In [92]:
x.max(axis=0)   # Maximum value of an array row

array([4, 5, 6])

In [94]:
x.cumsum(axis=1)  # Cumulative sum of the elements

array([[ 1,  3,  6],
       [ 4,  9, 15]])

In [96]:
x.mean()  # Mean

3.5

In [98]:
np.median(x)  # Median

3.5

In [99]:
np.corrcoef(x)  # Correlation coefficient

array([[1., 1.],
       [1., 1.]])

In [100]:
np.std(x)  # Standard deviation

1.707825127659933

### Copying Arrays

In [101]:
x = np.array([(1,2,3),(4,5,6)])

h = x.view()  # Create a view of the array with the same data

h

array([[1, 2, 3],
       [4, 5, 6]])

In [102]:
np.copy(x)  # Create a copy of the array

array([[1, 2, 3],
       [4, 5, 6]])

In [103]:
h = x.copy()  # Create a deep copy of the array

h

array([[1, 2, 3],
       [4, 5, 6]])

### Sorting Arrays

In [109]:
a = np.array([(10,2,1),(14,9,6)])

a

array([[10,  2,  1],
       [14,  9,  6]])

In [110]:
a.sort()  # Sort an Array
a

array([[ 1,  2, 10],
       [ 6,  9, 14]])

In [112]:
a.sort(axis=1)  # Sort the elements of an array's axis

a

array([[ 1,  2, 10],
       [ 6,  9, 14]])

### Subsettings, Slicing, Indexing

Subsettings

In [116]:
x = np.array([1,2,3,4,5])

x[1]  # Select the element at the 2nd index

2

In [115]:
y = np.array([(10,2,1),(14,9,6)])

y[1,2]  # Select the element at row 1 column 2 (equivalent to b[1][2])


6

Slicing

In [119]:
x[0:2]  # Select items at index 0 and 1

array([1, 2])

In [120]:
y[0:2,1]  # Select items at rows 0 and 1 in column 1

array([2, 5])

In [121]:
y[:1]  # Select all items at row 0 (equivalent to b[0:1, :])

array([[10,  2, 13]])

In [125]:
y[::-1]   # Reversed array 

array([[14,  5, 16],
       [10,  2, 13]])

Boolean Indexing

In [126]:
a = np.array([1,2,3,4,5])

a[a<2]  # Select elements from a less than 2

array([1])

Fancy Indexing

In [128]:
y = np.array([(10,2,1),(14,9,6)])

y[[1,0,0],[0,1,1]]

array([14,  2,  2])

### Array Manipulation

Transposing Array

In [130]:
x = np.array([(10,2,1),(14,9,6)])

i = np.transpose(x)   # Permute array dimensions

i

array([[10, 14],
       [ 2,  9],
       [ 1,  6]])

In [131]:
x.T  # Permute array dimensions

array([[10, 14],
       [ 2,  9],
       [ 1,  6]])

Changing Array Shape

In [132]:
y = np.array([(10,2,1),(14,9,6)])

y.ravel()  # Flatten the array

array([10,  2,  1, 14,  9,  6])

In [133]:
y.reshape(3,-2)  # Reshape, but don’t change data

array([[10,  2],
       [ 1, 14],
       [ 9,  6]])

Adding / Removing Elements

In [135]:
z = np.array([(10,2,1),(14,9,6)])

z.resize([2,6])  # Return a new array with shape (2,6)

z

array([[10,  2,  1, 14,  9,  6],
       [ 0,  0,  0,  0,  0,  0]])

In [136]:
np.append(z,y)  # Append items to an array

array([10,  2,  1, 14,  9,  6,  0,  0,  0,  0,  0,  0, 10,  2,  1, 14,  9,
        6])

In [137]:
np.insert(x, 1, 5)  # Insert items in an array

array([10,  5,  2,  1, 14,  9,  6])

In [139]:
z = np.array([(10,2,1),(14,9,6)])

np.delete(z,[1])  # Delete items from an array

array([10,  1, 14,  9,  6])

Combining Arrays

In [140]:
First_array = np.array([(1,2,3),(4,5,6)])

Second_array = np.array([(7,8,9),(10,11,12)])

np.concatenate((First_array,Second_array), axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [141]:
First_array = np.array([(1,2,3),(4,5,6)])

Second_array = np.array([(7,8,9),(10,11,12)])

np.vstack((First_array,Second_array))  # Stack arrays vertically (row-wise)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [142]:
First_array = np.array([(1,2,3),(4,5,6)])

Second_array = np.array([(7,8,9),(10,11,12)])

np.r_[First_array,Second_array]  # Stack arrays vertically (row-wise)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [145]:
np.hstack((First_array,Second_array)) # Stack arrays horizontally (column-wise)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [146]:
np.column_stack((First_array,Second_array))  # Create stacked column-wise arrays

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

Splitting Arrays

In [148]:
First_array = np.array([(1,2,3),(4,5,6)])

np.hsplit(First_array,3)  #Split the array horizontally at the 3rd index

[array([[1],
        [4]]),
 array([[2],
        [5]]),
 array([[3],
        [6]])]

In [149]:
Second_array = np.array([(7,8,9),(10,11,12)])

np.vsplit(Second_array,2)  # Split the array vertically at the 2nd index

[array([[7, 8, 9]]), array([[10, 11, 12]])]